# Generated by Django 4.2.6 on 2023-10-13 12:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField()),
                ('user_dob', models.DateField()),
                ('user_phone_code', models.CharField()),
                ('user_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('user_password', models.CharField()),
                ('user_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
