# Generated by Django 4.2.6 on 2023-10-13 12:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField()),
                ('user_dob', models.DateField()),
                ('user_phone_code', models.CharField()),
                ('user_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField()),
                ('user_verify', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
