# Generated by Django 4.2.6 on 2023-10-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tasks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created', 'complete']},
        ),
    ]
