# Generated by Django 4.2.6 on 2023-10-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tasks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['complete', '-created']},
        ),
    ]
