# Generated by Django 4.2.6 on 2023-10-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tasks_options_tasks_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['complete', 'priority', '-created']},
        ),
    ]
