# Generated by Django 4.2.6 on 2023-10-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_tasks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
